### PR TITLE
[ci] Remove everyday trigger

### PR DESCRIPTION
**Pull request by dlresende**
We are now running DRATS within the BBR CLI so maybe this is no longer necessary.

### CODE REVIEW

**Comment by totherme** [comment]
If the DRATS run inside the BBR CLI pipeline genuinely covers everything that this pipeline covers, then I agree. I might also argue that we can/should delete this pipeline altogether.

To figure out if we can safely delete this pipeline and lean only on the one in BBR-CLI, I think we need to know:
- what happens if DRATS gets updated/PRed ?
- are there any "extra bits" that this pipeline tests, which the BBR CLI pipeline doesn't test?

**Comment by dlresende** [comment]
> what happens if DRATS gets updated/PRed ?

Nothing would happen. I see this pipeline as testing the DRATS CI itself, helping us build the DRATS product. We are using DRATS on BBR, by at that point is more like consuming product IMO.

> are there any "extra bits" that this pipeline tests, which the BBR CLI pipeline doesn't test?

Not that I'm aware of. But this pipeline separates the various bits a PR has to go through. In the BBR pipeline all the DRATS bits are squashed into a single job, which might be hard to debug.

I am of the opinion we should keep this pipeline for the time being. Just that because we have it being used in the BBR CLI pipeline, I think we let the everyday trigger go though.

**Comment by rkoster** [comment]
@dlresende is this PR still being worked on? If so could you maybe convert it into a draft? So it does not show up on the review board?

**Comment by dlresende** [comment]
> If the DRATS run inside the BBR CLI pipeline genuinely covers everything that this pipeline covers, then I agree. 

Hey @totherme. I'll merge this PR for now as I believe the statement above is true.

**Pull request merged**
